# Quotes for AutoBio 

# English Quotes 
ENGLISH_QUOTES = [

    "Best way to earn respect is By treating others with respect ",
    "Win in silence. Let them think you're losing. ",
    "The biggest slap to your enemies is your success.‌‌ ",
    "Winners never quit and Quitters Never win. ",
    "And if you love, love their darkness too, not just their light. ",
    "Sometimes losing people makes you find yourself. ",
    "Belive in yourself. You will survive whatever is coming. ",
    "is here any sweet is being sold here, you came to see. ",
    "Do something today that your future self will thank you for. ",
    "Don't forget God when you get what you've prayed for. ",
    "Be happy with what you have, while working for what you want. ",
    "You can only win when your mind is stronger than your emotions. ",
    "Keep your dreams big and your worries small. ",
    "If someone makes you happy, make them happier. ",
    "Tag a friend who has been with you in your hard times. ",
    "Winning isn't everything, but wanting to win is. ",
    "If you interested to read bio's, then why not take bio. ",
    "A champion is someone who gets up when he can't. ",
    "If you can believe it, the mind can achieve it. ",
    "Game doesn't build character, it reveals character! ",
    "If you train hard, you'll not only be hard, you'll be hard to beat. ",
    "You win some, lose some, and wreck some. ",
    "Age is no barrier. It's a limitation you put on your mind. ",
    "Nobody roots for Goliath. ",
    "Set your goals high, and don't stop till you get there. ",
    "Statistics are like bikinis—they show a lot but not everything. ",
    "You miss 100 percent of the shots you don't take. ",
    "The way to get started is to quit talking and begin doing. ",
    "Your time is limited, so don't waste it living someone else's life. ",
    "That which does not kill us makes us stronger. "]
